name: manage-azure-policy-92c54f02
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Deploy_Log_Analytics_agent_-_East_US_6e7c542c3a2744c9a3e53fb2/**'
#      - 'initiatives/Deploy_Log_Analytics_agent_-_West_US_4a4fe91b35c1406bbba279cb/**'
#      - .github/workflows/manage-azure-policy-92c54f02.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_92c54f02}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Deploy_Log_Analytics_agent_-_East_US_6e7c542c3a2744c9a3e53fb2/**
          initiatives/Deploy_Log_Analytics_agent_-_West_US_4a4fe91b35c1406bbba279cb/**
